# Generated by Django 3.2.9 on 2021-11-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SongTracks',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=100)),
                ('track_name', models.CharField(max_length=100)),
                ('artist_name', models.CharField(max_length=100)),
                ('popularity', models.IntegerField()),
                ('valence', models.FloatField()),
                ('energy', models.FloatField()),
                ('danceability', models.FloatField()),
                ('acousticness', models.FloatField()),
                ('tempo', models.FloatField()),
                ('speechiness', models.FloatField()),
                ('mode', models.IntegerField()),
                ('instrumentalness', models.FloatField()),
            ],
        ),
    ]
